### ISSUE TITLE
Fix issue with Decryption

### ISSUE THREAD

**Issue by kupokev** [kupokev/EnKrypt#2]
There is an issue where the decryption doesn't work when you use mixed cases. I think it is related to .contains and finding the letters in the alphabet array, but have not had a chance to look into it.

**Comment by mbrajk** [comment]
Did some testing with this and I don't think your issue is only related to mixed case, although it does seem have some effect, especially at the beginning and end of the input string. See below for my tests with and without mixed cases and their results.

### No mixed case
- "abcdefghijkl" passes
- "abcdefghijklm" fails
- "this is a test string" fails
  - Decrypts to "this is  test string" (note the missing "a", actually decrypts to a double space). This is also the only test I've done that fails and is still basically readable

### Mixed case
- "This is a test string" fails
- "tHiS Is a tEsT StRiNg" passes
- "tHIS IS A TEST STRING" fails
- "tHIS IS A TEST STRINg" passes
- "thIs Is a tEsT StRiNg" fails
- "thIs Is an tEsT StRiNg" passes (note the change to "an" from "a")

**Comment by kupokev** [comment]
I did some testing finally. First I took the first section of the string "This is a test string" since I knew this was not decrypting correctly. The results are below:

Application returned:
"tsrnihgeaT "
20635089221466807464649
6EAURS6MKSNAEG09

 [0] 't'
 [1] 's'
 [2] 'r'
 [3] 'n'
 [4] 'i'
 [5] 'h'
 [6] 'g'
 [7] 'e'
 [8] 'a'
 [9] 'T'
[10] ' '

String 1: "This is " ( 206350892)
String 2: "a test st" (2146680746)
String 3: "ring" (4649)

[0] 'T':
(11 ^ (8 - 1)) \* (9 + 1) = 194,871,710

[1] 'h':
(11 ^ (8 - 2)) \* (5 + 1) = 10,629,366

[1] 'i':
(11 ^ (8 - 3)) \* (4 + 1) = 805,255

[1] 's':
(11 ^ (8 - 4)) \* (1 + 1) = 29,282

[1] ' ':
(11 ^ (8 - 5)) \* (10 + 1) = 14,641

[1] 'i':
(11 ^ (8 - 6)) \* (4 + 1) = 605

[1] 's':
(11 ^ (8 - 7)) \* (1 + 1) = 22

[1] ' ':
(11 ^ (8 - 8)) \* (10 + 1) = 11

Total: 206,350,892

As shown above, the first integer is "206350892". The issue with the decryption process is it looks for the largest number below integer max of 2,147,483,647. In this case the max number is 2,063,508,922 which is not the actual first integer value we are looking for.

**Comment by kupokev** [comment]
"This is a test string" passes
"tHiS Is a tEsT StRiNg" passes
"tHIS IS A TEST STRING" passes
"tHIS IS A TEST STRINg" passes
"thIs Is a tEsT StRiNg" passes
"thIs Is an tEsT StRiNg" passes

I believe I have fixed the issues causing these failures. Please verify if you get a moment. Thank you.
